[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200